forms.py
#forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired

class ScenarioForm(FlaskForm):
    choice = SelectField('Choose Decision', choices=[], coerce=str)
    def __init__(self, choices=None, **kwargs):
        super(ScenarioForm, self).__init__(**kwargs)
        if choices:
            self.choice.choices = choices
            
class NewGameForm(FlaskForm):
    name = StringField('', validators=[DataRequired()])
    submit = SubmitField('Start New Game')

class DifficultyForm(FlaskForm):
    difficulty = SelectField('Choose Difficulty', choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard'), ('hardcore', 'Hardcore')])

class UniversityForm(FlaskForm):
    university_type = SelectField('Choose University Type', choices=[('public', 'Public'), ('private', 'Private')])

class ProgramForm(FlaskForm):
    program = SelectField('Choose Program', choices=[('civil_engineering', 'Civil Engineering'), ('nursing', 'Nursing'), ('computer_science', 'Computer Science'), ('fine_arts', 'Fine Arts')])

class DormForm(FlaskForm): 
    dorm_type = SelectField('Choose Dorm Type', choices=[('solo_room', 'Solo Room'), ('bed_space', 'Bed Space')])
    


app.py
#app.py

from flask import Flask
from views import index

app = Flask(__name__)
app.config['SECRET_KEY'] = 'bampeepmab'

app.register_blueprint(index)

main.py
#main.py

from app import app

if __name__ == "__main__":
    app.run(debug=True, port=8000)

views.py
#views.py

from flask import Blueprint, render_template, redirect, url_for
from forms import NewGameForm, DifficultyForm, UniversityForm, ProgramForm, DormForm, ScenarioForm
from game_logic import GameLogic
from scenarios import SCENARIO_DATA, Scenario

index = Blueprint('index', __name__)

game_logic = GameLogic()

@index.route('/')
def home():
    game_logic.initialize_users_table()
    game_logic.__init__()
    return render_template('menu.html')

@index.route('/new_game', methods=['GET', 'POST'])
def new_game():
    form = NewGameForm()
    if form.validate_on_submit():
        player_name = form.name.data
        game_logic.initialize(player_name)
        return redirect(url_for('index.difficulty'))
    return render_template('new_game.html', form=form)

@index.route('/leaderboard')
def leaderboard():
    leaderboard_data = game_logic.get_leaderboard()
    return render_template('leaderboard.html', players=leaderboard_data)
     
@index.route('/quit_game')
def quit_game():
    # Add any necessary cleanup logic here
    return render_template('quit_game.html')

@index.route('/difficulty', methods=['GET', 'POST'])
def difficulty():
    form = DifficultyForm()
    if form.validate_on_submit():
        difficulty = form.difficulty.data
        game_logic.set_difficulty(difficulty)
        return redirect(url_for('index.university'))
    return render_template('difficulty.html', form=form, game=game_logic)

@index.route('/university', methods=['GET', 'POST'])
def university():
    form = UniversityForm()
    if form.validate_on_submit():
        university_type = form.university_type.data
        game_logic.set_university(university_type)
        return redirect(url_for('index.program'))
    return render_template('university.html', form=form)

@index.route('/program', methods=['GET', 'POST'])
def program():
    form = ProgramForm()
    if form.validate_on_submit():
        program = form.program.data
        game_logic.set_program(program)
        return redirect(url_for('index.dorm'))
    program_costs = {
        'public': {
            'easy': {'civil_engineering': 60000, 'nursing': 80000, 'computer_science': 40000, 'fine_arts': 80000},
            'normal': {'civil_engineering': 80000, 'nursing': 100000, 'computer_science': 60000, 'fine_arts': 100000},
            'hard': {'civil_engineering': 120000, 'nursing': 140000, 'computer_science': 100000, 'fine_arts': 140000}
        },
        'private': {
            'easy': {'civil_engineering': 80000, 'nursing': 100000, 'computer_science': 60000, 'fine_arts': 100000},
            'normal': {'civil_engineering': 100000, 'nursing': 120000, 'computer_science': 80000, 'fine_arts': 120000},
            'hard': {'civil_engineering': 140000, 'nursing': 160000, 'computer_science': 120000, 'fine_arts': 160000},
            'hardcore': {'civil_engineering': 200000, 'nursing': 220000, 'computer_science': 180000, 'fine_arts': 220000}
        }
    }

    return render_template('program.html', form=form, university=university, difficulty=difficulty, program_costs=program_costs)


@index.route('/dorm', methods=['GET', 'POST'])
def dorm():
    form = DormForm()
    if form.validate_on_submit():
        dorm_type = form.dorm_type.data
        game_logic.set_dorm(dorm_type)
        return redirect(url_for('index.scenarios', scenario_key= 'AA', scenario_next_key='AA'))
    return render_template('dorm.html', form=form)

@index.route('/scenarios/<scenario_key>/<scenario_next_key>', methods=['GET', 'POST'])
def scenarios(scenario_key, scenario_next_key):
    scenario = SCENARIO_DATA.get(scenario_key)

    if scenario and isinstance(scenario, Scenario):
        choices = scenario.options
        form = ScenarioForm(choices=choices)

        if form.validate_on_submit():
            answer = form.choice.data
            game_logic.set_scenario(answer, *scenario.outcomes[answer])
            return redirect(url_for('index.scenarios', scenario_key=scenario_next_key, scenario_next_key=scenario_next_key))

        return render_template(f'scenario{scenario_next_key}.html', form=form, game=game_logic)

    return redirect(url_for('index.home'))  # Redirect to home if scenario_key is not found

@index.route('/scenarios/<scenario_key>', methods=['GET', 'POST'])
def get_result(scenario_key):
    scenario = SCENARIO_DATA.get(scenario_key)

    if scenario and isinstance(scenario, Scenario):
        choices = scenario.options
        form = ScenarioForm(choices=choices)

        if form.validate_on_submit():
            answer = form.choice.data
            game_logic.set_scenario(answer, *scenario.outcomes[answer])
            return redirect(url_for('index.result'))  # Include scenario_key parameter

        return render_template(f'scenario{scenario_key}.html', form=form, game=game_logic)

    return redirect(url_for('index.home'))  # Redirect to home if scenario_key is not found


@index.route('/scenarios', methods=['GET', 'POST'])
def result():
    game_logic.set_result()
    return render_template('result.html', game=game_logic)

templates/difficulty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Debt Threat</title>
    <link rel="icon" type="image/x-icon" href="https://i.ibb.co/jzPQFRv/image-removebg-preview-1.png">
    <audio id="INTRO" src="{{ url_for('static', filename='INTRO.mp3') }}" autoplay></audio>
    
    <style>
        body {
            background-image: url('https://i.ibb.co/f4zFmRR/enlarge-cover.png');
            background-attachment: fixed;
            background-size: cover;
            background-position: center;
            background-repeat: repeat;
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            height: 100vh;
        }

        @font-face {
            font-family: Minecraftory;
            src: url("{{ url_for('static', filename='Minercraftory.ttf') }}");
        }

        @keyframes fadeIn {
            0% { opacity: 0; }
            100% { opacity: 1; }
        }

        .container {
            font-family: Minecraftory;
            max-width: 900px;
            margin-top: 170px;
            background-color: rgb(82, 5, 5);
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(255, 255, 255, 0.782);
            animation: fadeIn 2s; 
            display: flex;
        }

        .container2 {
            font-family: Minecraftory;
            width: 600px;
            margin-top: 10px;
            background-color: rgb(82, 5, 5);
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(255, 255, 255, 0.782);
            animation: fadeIn 2s; 
        }


        .left-container {
            width:20%;

        }
        .right-container {
            width:80%;
            box-sizing: border-box;
        }

        .right-container p {
            font-size: 13px;
            text-align: justify;
            color: #ffffff;
            margin-top: 10px;
        }

        h1 {
            font-family: Minecraftory;
            text-align: center;
            color: #ffffff;
            font-size: 1.5em;
            margin-top: 20px;
        }

        .radio-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-top: 10px;
        }

        label {
            font-family: Minecraftory;
            font-size: 0.5em;
            color: #fff;
            margin-bottom: 10px;
        }

        input[type="radio"] {
            display: none;
        }

        button {
            font-family: Minecraftory;
            background-color: #000000;
            color: #fff;
            padding: 10px 20px;
            width: 200px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: transform 0.3s ease;
            display: block;
            margin-bottom: 10px;
        }

        button:hover {
            color:black;
            background-color: white;
            transform: scale(1.1);
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="left-container">
            <img src="https://i.ibb.co/HN1Rchm/ezgif-com-crop.gif" width="90px" height="130px">
        </div>
        <div class="right-container">
            <p>Welcome {{ game.player_name }}, You are a student from a low-class family in the Philippines, desperate to pursue a college degree and secure a job that will suffice all your necessities. However, the only way for you to be able to study is to get a student loan worth 500,000 from a criminal syndicate. Your goal is to finish your chosen program while also using your monetary loan frugally and pay off this debt in your first job salary. Otherwise, yours and your family's life will be at stake.</p>
        </div>
    </div>
    <div class="container2">
    <h1>Choose your mode</h1>
    <form method="POST" action="{{ url_for('index.difficulty') }}">
        {{ form.hidden_tag() }}
        <div class="radio-container">
            {% for radio in form.difficulty %}
                <label>
                    <button type="radio" name="{{ form.difficulty.name }}" value="{{ radio.data }}">
                        {{ radio.label.text }}
                    </button>
                </label>
            {% endfor %}
        </div>
    </div>
    </form>
</body>
</html>

templates/new_game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Game</title>
    <link rel="icon" type="image/x-icon" href="https://i.ibb.co/jzPQFRv/image-removebg-preview-1.png">
    
    <style>
        @font-face {
            font-family: Minecraftory;
            src: url("{{ url_for('static', filename='Minercraftory.ttf') }}");
        }
        @keyframes fadeIn {
            0% { opacity: 0; }
            100% { opacity: 1; }
        }

        body {
            background-image: url('https://i.ibb.co/f4zFmRR/enlarge-cover.png');
            background-attachment: fixed;
            background-size: cover;
            background-position: center;
            background-repeat: repeat;
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            height: 100vh;
        }

        .container {
            font-family: Minecraftory;
            max-width: 1000px;
            margin-top: 170px;
            background-color: rgb(82, 5, 5);
            padding: 50px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(255, 255, 255, 0.782);
            animation: fadeIn 2s; 
        }

        h1, form {
            font-family: Minecraftory;
            text-align: center;
            color: #ffffff;
            font-size: 1.5em;
            background-color: rgba(125, 187, 196, 0.514); /* Adjust transparency here */
            padding: 8px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-top: 12px; /*margin in the taas*/
        }
        h2, form {
            font-family: Minecraftory;
            color: #f1eaea; 
            font-size: 1em;
         }
        form {
            text-align: center;
            background-color: rgb(82, 5, 5);
            padding: 50px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 7px;
        }

        input[type="text"] {
            font-family: Minecraftory;
            text-align: center;
            background-color: #f0f0f0; /*kung balak paltan yung color ng lalagyn ng username*/
            font-size: 0.9em;
            width: 200px;
            padding:7px;
            margin-bottom: 15px;
            box-sizing: border-box;
            border: 3px solid #140505;
            border-radius: 4px;
        }

        input[type="submit"] {
            font-family: Minecraftory;
            background-color: #000000;
            color: white;
            padding: 10px 25px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        input[type="submit"]:hover {
            background-color: #ffffff;
            color:#000000;
        }
    </style>
</head>
<body>
    <div class="container">
       
        <form method="POST" action="{{ url_for('index.new_game') }}">
            <center>
            <img src="https://i.ibb.co/j6zC0X3/ezgif-4-241998eeff.gif" height="150" width="140" /> </center>
            <h1>NEW GAME</h1>
            {{ form.hidden_tag() }}
            {{ form.name.label }}
            {{ form.name(placeholder='Player Name') }}
            <br>
            <input type="submit" value="Submit">
        </form>
        
        
    </div>
</body>
</html>


templates/program.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose Program</title>
    <link rel="icon" type="image/x-icon" href="https://i.ibb.co/jzPQFRv/image-removebg-preview-1.png">
       
    <style>
        body {
            background-image: url('https://i.ibb.co/f4zFmRR/enlarge-cover.png');
            background-attachment: fixed;
            background-size: cover;
            background-position: center;
            background-repeat: repeat;
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        @font-face {
            font-family: Minecraftory;
            src: url("{{ url_for('static', filename='Minercraftory.ttf') }}");
        }
        
         @keyframes fadeIn {
            0% { opacity: 0; }
            100% { opacity: 1; }
        }

        h1 {
            font-family: Minecraftory;
            text-align: center;
            color: #ffffff;
            font-size: 50px;
        }

        form {
            display: flex;
            font-size: 30px;
            flex-direction: column;
            align-items: center;
        }

        .program-options {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        label {
            position: relative;
            margin: 10px;
            cursor: pointer;
        }

        button {
            position: relative;
            padding: 20px;
            width: 276px; /* Set a width for a rectangular shape */
            height: 223px;
            border-radius: 8px;
            box-shadow: 0 0 15px rgba(255, 255, 255, 0.3);
            border-radius: 8px;
            transition: background 0.3s; /* Smooth transition on hover */
            transition: opacity 0.3s; /* Smooth transition on hover */
            overflow: hidden; /* Ensure overflow is hidden to contain the image */
            background: rgba(139, 0, 0, 0.7); /* DarkRed with reduced opacity */
            animation: fadeIn 2s; 
        }

        .course-title {
            position: relative;
            z-index: 2;
            color: white;
            opacity: 0;
            transition: opacity 0.3s;
        }

        .course-image {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 40%;
            height: 45%;
            object-fit: cover;
            z-index: 1;
        }

        /* Images for each program */
        button[data-program="Civil Engineering"] .course-image {
            content: url("https://i.ibb.co/pf8Ftx1/px-Art-17.png");
        }

        button[data-program="Nursing"] .course-image {
            content: url("https://i.ibb.co/BjmQZSn/px-Art-14.png"); 
        }

        button[data-program="Computer Science"] .course-image {
            content: url("https://i.ibb.co/R7tYY0x/Px-Art-12.png");
        }

        button[data-program="Fine Arts"] .course-image {
            content: url("https://i.ibb.co/6Pskh3R/px-Art-16.png"); 
        }

        button:hover .course-title {
            opacity: 1; /* Show the title on hover */
        }

        button:hover {
            opacity: 0.8;
            background-color: #1d0202;
            font-family: Minecraftory;
        }

        button:hover .course-image {
            opacity: 0; /* Hide the image on hover */
        }
    </style>
</head>
<body>
    <h1>Choose Program</h1>
    <form method="POST" action="{{ url_for('index.program') }}">
        {{ form.hidden_tag() }}
        <div class="program-options">
            {% set course_images = {
                'Civil Engineering': 'path_to_civil_engineering_image.jpg',
                'Nursing': 'path_to_nursing_image.jpg',
                'Computer Science': 'path_to_computer_science_image.jpg',
                'Fine Arts': 'path_to_fine_arts_image.jpg'
            } %}
            
            {% for radio in form.program %}
                <label>
                    <button type="radio" name="{{ form.program.name }}" value="{{ radio.data }}" data-program="{{ radio.label.text }}">
                        <img class="course-image" src="{{ course_images[radio.label.text] }}" alt="Course Image">
                        <div class="course-title">{{ radio.label.text }}</div>
                    </button>
                </label>
            {% endfor %}
        </div>
    </form>
</body>
</html>

templates/scenarioDD.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>College Journey</title>
    <link rel="icon" type="image/x-icon" href="https://i.ibb.co/jzPQFRv/image-removebg-preview-1.png">
    <audio id="voiceDD" src="{{ url_for('static', filename='voiceDD.mp3') }}" autoplay></audio>
    
    <style>
        @font-face {
            font-family: Minecraftory;
            src: url("{{ url_for('static', filename='Minercraftory.ttf') }}");
        }

        @keyframes fadeIn {
            0% { opacity: 0; }
            100% { opacity: 1; }
        }

        @keyframes typing {
            from { width: 0; }
            to { width: 100%; }
        }

        body {
            background-image:url("{{ url_for('static', filename='sceneDD.jpg') }}");
            background-attachment: fixed;
            text-align: right;
            background-size: cover;
            background-position: center;
            background-repeat: repeat;
            margin: 0;
            padding: 0;
        }

        .intro-text {
            position: fixed;
            right: 60px;
            top: 10px;
            width: 1000px;
            height: 80px;
            padding: 10px;
            border-radius: 8px;
            background-color: rgba(28, 20, 39, 0.8);
            color: white;
            font-family: Minecraftory;
            font-size: 18px;
            text-align: center;
            border: 3px outset #000000;  
            opacity: 0;
            animation: fadeIn 2s forwards; 
        }

        progress {
            width: 13%; 
            height: 25px;
            margin-top: 8px;
            border-radius: 3px;
            border-style: solid;
            border-color: black;    
            position: relative;
        }

        progress::after {
            font-family: Minecraftory;
            content: attr(value); /* Display the value as content */
            position: absolute;
            top: 50%; /* Adjust the vertical position as needed */
            left: 50%; /* Adjust the horizontal position as needed */
            transform: translate(-50%, -50%);
            color: white; /* Adjust the text color as needed */
            font-size: 10px; /* Adjust the font size as needed */
        }

        .progress-container {
            top: 150px; 
            display: flex;
            align-items: center;
            margin-bottom: 3px;
        }

        .progress-name {
            font-family: Minecraftory;
            color: aliceblue;
            font-size: 13px;
            margin-left: 15px;
            margin-right: 15px;
            min-width: 120px; /* Set a minimum width for the progress names */
        }

        .progress-value {
            font-family: Minecraftory;
            color: aliceblue;
            font-size: 10px;
            margin-left: 10px;
        }

        .debt-progress::-webkit-progress-value {
            background: #000000;
        }

        .debt-money-progress::-webkit-progress-value {
            background: #1B1F3A;
        }

        .education-progress::-webkit-progress-value {
            background: #53354A;
        }

        .health-progress::-webkit-progress-value {
            background: #A64942;
        }

        .happiness-progress::-webkit-progress-value {
            background: #582233;
        }

        button {
            font-family: Minecraftory;
            font size: 15px;
            color: #E7DFD5;
            background: rgba(89, 0, 0);
            position: relative;
            top: 170px;
            padding: 20px;
            width: 276px; 
            height: 223px;
            right: 250px;
            margin-right: 60px;
            box-shadow: 0 0 20px rgba(0 , 0, 0, 0.7);
            border-radius: 8px;
            border: 4px ridge rgb(66, 5, 22, 0.3);           
             cursor: pointer;
            transition: transform 0.2s;
            animation: fadeIn 2s;  
        }

        button:hover {
            transform: scale(1.1);
        }

        button:active {
            font-size: 20px;
        }
        .whisper-container {
            position: fixed;
            bottom: 20px;
            right: 70px;
            width: 1000px;
            height: 140px;
            padding: 10px;
            border-radius: 8px;
            background-color: rgba(44, 57, 75, 0.8);
            border: 3px outset #000000;  
            color: white;
            font-family: Minecraftory;
            font-size: 22px;
            text-align: justify;
            opacity: 0; /* Start with opacity 0 */
            animation: fadeIn 2s forwards; /* Apply the fadeIn animation */
            white-space: pre-line; /* Preserve newlines in the text */
            overflow: hidden; /* Hide the overflow text */
        }

        .whisper-container::before {
            content: "The big day's here. Do you want to own the moment with a brand-new graduation set, or keep it practical and rent one for the day?";
            animation: typing 5s steps(100, end), fadeIn 2s forwards;
            white-space: pre-line; /* Preserve newlines in the text */
        }
    </style>
    
</head>
<body>

    <div class="intro-text">
        The culmination of your hard work has arrived. What attire do you plan to wear on this momentous occasion?
    </div>

    <div class="progress-container">
        <span class="progress-name">Debt Money:</span>
        <progress class="debt-money-progress" value="{{ game.debt_money }}" max="500000">{{ game.debt_money }}</progress>
        {% if game.debt_money_cost != 0 %}
            <span class="progress-value" style="color: {% if game.debt_money_cost < 0 %}red{% else %}green{% endif %};">
                {{ game.debt_money_cost }}
            </span>
        {% endif %}
    </div>
    <div class="progress-container">
        <span class="progress-name">Education:</span>
        <progress class="education-progress" value="{{ game.education }}" max="100">{{ game.education }}</progress>
        {% if game.education_cost != 0 %}
            <span class="progress-value" style="color: {% if game.education_cost < 0 %}red{% else %}green{% endif %};">
                {{ game.education_cost }}
            </span>
        {% endif %}
    </div>
    <div class="progress-container">
        <span class="progress-name">Health:</span>
        <progress class="health-progress" value="{{ game.health }}" max="100">{{ game.health }}</progress>
        {% if game.health_cost != 0 %}
            <span class="progress-value" style="color: {% if game.health_cost < 0 %}red{% else %}green{% endif %};">
                {{ game.health_cost }}
            </span>
        {% endif %}
    </div>
    <div class="progress-container">
        <span class="progress-name">Happiness:</span>
        <progress class="happiness-progress" value="{{ game.happiness }}" max="100">{{ game.happiness }}</progress>
        {% if game.happiness_cost != 0 %}
            <span class="progress-value" style="color: {% if game.happiness_cost < 0 %}red{% else %}green{% endif %};">
                {{ game.happiness_cost }}
            </span>
        {% endif %}
    </div>
    
    <form method="POST" action="{{ url_for('index.get_result', scenario_key = 'DD') }}">
        {{ form.hidden_tag() }}
        <div>
            {% for choice, label in form.choice.choices %}
                <label>
                    <button type="radio" name="{{ form.choice.name }}" value="{{ choice }}" style="font-size: 16px; padding: 10px;">
                        {{ label }}
                    </button>
                </label>
            {% endfor %}
        </div>
    </form>
    <div class="whisper-container"></div>
</body>
</html>

templates/university.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose University</title>
    <link rel="icon" type="image/x-icon" href="https://i.ibb.co/jzPQFRv/image-removebg-preview-1.png">
        
    <style>
        body {
            background-image: url('https://i.ibb.co/f4zFmRR/enlarge-cover.png');
            background-attachment: fixed;
            background-size: cover;
            background-position: center;
            background-repeat: repeat;
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        @font-face {
            font-family: Minecraftory;
            src: url("{{ url_for('static', filename='Minercraftory.ttf') }}");
        }

        @keyframes fadeIn {
            0% { opacity: 0; }
            100% { opacity: 1; }
        }

        h1 {
            font-family: Minecraftory;
            text-align: center;
            color: #ffffff;
            font-size: 50px;
        }

        form {
            display: flex;
            font-size: 30px;
            flex-direction: column;
            align-items: center;
        }

        label {
            position: relative;
            margin: 10px;
            cursor: pointer;
        }

        button {
            position: relative;
            padding: 20px;
            width: 276px;
            height: 223px;
            border-radius: 8px;
            box-shadow: 0 0 15px rgba(255, 255, 255, 0.3);
            border-radius: 8px;
            transition: background 0.3s, opacity 0.3s;
            background: rgba(139, 0, 0, 0.7);
            animation: fadeIn 2s;
        }

        .university-title {
            position: relative;
            font-family: Minecraftory;
            z-index: 2;
            color: white;
            opacity: 1;
            transition: opacity 0.3s;
        }

        .university-image {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 59%;
            height: 70%;
            object-fit: cover;
            z-index: 1;
            opacity: 0;
            transition: opacity 0.3s;
        }

        button[data-university="Public"] .university-image {
            content: url("https://i.ibb.co/1RXb56r/image-removebg-preview-2.png");
        }

        button[data-university="Private"] .university-image {
            content: url("https://i.ibb.co/qWMCvvJ/image-removebg-preview-3-1.png");
        }

        button:hover .university-title {
            opacity: 0;
        }

        button:hover .university-image {
            opacity: 1;
        }

        button:hover {
            opacity: 0.8;
            background-color: #1d0202;
        }
    </style>
</head>
<body>
    <h1>Choose University</h1>
    <form method="POST" action="{{ url_for('index.university') }}">
        {{ form.hidden_tag() }}
        <div class="program-options">
            {% for radio in form.university_type %}
                <label>
                    <button type="radio" name="{{ form.university_type.name }}" value="{{ radio.data }}" data-university="{{ radio.label.text }}">
                        <div class="university-title">{{ radio.label.text }}</div>
                        <img class="university-image" src="" alt="University Image">
                    </button>
                </label>
            {% endfor %}
        </div>
    </form>
</body>
</html>